// <auto-generated />
using System;
using Senior_Design_Pet_Care_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Senior_Design_Pet_Care_App.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20251001180941_SeedAdminUser")]
    partial class SeedAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Senior_Design_Pet_Care_App.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 18, 9, 40, 886, DateTimeKind.Utc).AddTicks(7518),
                            Email = "admin@gmail.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEHO2elUU+yppjQ4BcZ5sRvwe4R7ZYK9FYplVGfKA7a6lfh2My2TyD5Sy7rNh2oAeTw==",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
